- name: Copy files
  hosts: servers
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: copying hosts file
      copy:
        src: ../files/hosts 
        dest: /etc/hosts
    - name: Copying slurm.conf file
      copy:
        src: ../files/slurm.conf
        dest: /etc/slurm/
    - name: Changing directory permisssions
      file:
        dest: /var/share/slurm/
        owner: slurm 
        group: slurm
        mode: 0755
        recurse: yes
